# Generated by Django 5.2.6 on 2025-09-14 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/teams/')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FT', 'Full Time'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='main_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='main_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(blank=True, max_length=80)),
                ('p_home', models.FloatField(blank=True, null=True)),
                ('p_draw', models.FloatField(blank=True, null=True)),
                ('p_away', models.FloatField(blank=True, null=True)),
                ('pick', models.CharField(blank=True, choices=[('HOME', 'Home'), ('DRAW', 'Draw'), ('AWAY', 'Away')], max_length=5, null=True)),
                ('stake', models.FloatField(default=1.0)),
                ('result_points', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='main_app.match')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'user', 'model_key'], name='main_app_pr_match_i_d95b92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['kickoff_at'], name='main_app_ma_kickoff_287336_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='main_app_ma_status_34e37e_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='no_same_team'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'kickoff_at')},
        ),
    ]
